// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

const fibonacci_sequence = (a, b) => {
  let temp;
  let fibs = [];

  while (b < 4000000) {
    temp = a;
    a = a + b;
    b = temp;
    if (b % 2 === 0) {
      fibs.push(b);
    }
    console.log(b);
  }
  const answer = fibs.reduce(sum);
  console.log('ANSWER: ', answer);
  return answer;
};

const sum = (acc, cur) => {
  return acc + cur;
};

fibonacci_sequence(1, 1);
